### POST request new user
POST http://localhost:8080/v1/users
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### POST login with user admin
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

<> 2024-10-15T234616.200.json

### GET request list all users
GET http://localhost:8080/v1/users
Accept: application/json
Authorization: Bearer {{token}}

<> 2024-10-15T234850.200.json

### GET all by filter
GET http://localhost:8080/v1/todos?status=IN_PROGRESS
Accept: application/json
Authorization: Bearer {{token}}

### POST create new todo
POST http://localhost:8080/v1/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Todo 7",
  "description": "Descricao 7"
}

### PUT change status of todo
PUT http://localhost:8080/v1/todos/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "COMPLETED"
}

### DELETE deletar todo
DELETE http://localhost:8080/v1/todos/5
Content-Type: application/json
Authorization: Bearer {{token}}